blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://github.com/Nathanielneil/TriModalFusion/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issues
    url: mailto:guowei_ni@bit.edu.cn
    about: Report security vulnerabilities privately
  - name: Documentation
    url: https://github.com/Nathanielneil/TriModalFusion/tree/main/docs
    about: Read the documentation before opening an issue